### ISSUE TITLE
CMake and Ninja versions necessary

### ISSUE THREAD

**Issue by waarmond** [EmilDohne/PhotoshopAPI#68]
I'm using Python 3.10, cmake 3.29.1 and ninja 1.11.1. I usually try first with my own versions to avoid env balkanization.

With meson 1.3.0:
```
running build_ext
Traceback (most recent call last):
  File "./PhotoshopAPI/setup.py", line 153, in <module>
    setup(
[..]
    ninja_executable_path = Path(ninja.BIN_DIR) / "ninja"
AttributeError: module 'ninja' has no attribute 'BIN_DIR'
```

After updating to meson 1.4.0:
```
ERROR Missing dependencies:
	ninja
	cmake>=3.12
```

Which versions do you recommend?

**Comment by EmilDohne** [comment]
Hey, I am not too familiar with the meson build system myself but I am personally running using ninja 1.11.0 through visual studio. Are you intending on building the wheels or the compiled `.pyd` yourself? 

For the `.pyd` you only need to build via cmake while the wheels rely on the `setup.py` file. I myself only build the wheels through CI which is why I dont have a local example to go off of

**Comment by EmilDohne** [comment]
Hi @waarmond, I just wanted to check in if you were able to get it working?
