### ISSUE TITLE
Ability to create .psd files

### ISSUE THREAD

**Issue by Gofven** [EmilDohne/PhotoshopAPI#96]

**Comment by EmilDohne** [comment]
Hey @Gofven , the PhotoshopAPI fully supports both psd and psb file formats. It will usually just deduce the file format based on what extension you pass to the LayeredFile.write method. Are you using python or c++?

**Comment by Gofven** [comment]
Waah i accidentally pressed enter or an uncomplete issue, my bad! But i do indeed have a certain issue with it (o also thanks for the blazing fast response!!)

I'm attempting to create an ImageLayer_8bit layer and add it to a new LayeredFile_8bit instance, then write the data to a directory. When attempting this operation, i do end up with a successful export, however the psd file is completely unreadable when i'm attempting to use Krita to read it.

Do you have any suggestions to why this may occur c:? I do have a rather messy file that i've been attempting to fix by trial and error (before i start cleaning it up), but to no avail, here it is if you'd like to see more on the issue: https://www.toptal.com/developers/hastebin

**Comment by EmilDohne** [comment]
No worries, its definitely happened to me too ;). Im not too familiar with krita but id be happy to look into it. I've so far not run into any issues with psds/psbs written by the PhotoshopAPI (except for files with only groups) but the format is a fiddly one and there is many exceptions.

I think you accidentally sent an empty pastebin but I'll take a look once you've sent it! Since krita is open source I can also then just hook up a debugger to it and tell exactly whats wrong

**Comment by Gofven** [comment]
my bad, here's the URL!
https://hastebin.com/share/huvuroveyo.kotlin

**Comment by EmilDohne** [comment]
Thanks for the link! I'll try running it once back home and then seeing if photoshop can open the imagefile and if its krita specific or psapi but from a first glance it looks like it should work.

Fyi youre probably better off using numpy slicing operations for getting the image data in the right format rather than looping over the images pixel by pixel :)

**Comment by Gofven** [comment]
No problem c:
Also yes going pixel by pixel wasn't the greatest solution, given how slow it is. I read on the numpy docs and decided to use swapaxes, just the line `image_data.swapaxes(0, 2)` and it's good to go c:

_Although the same issue persist so i'm not quite sure whether the swap actually works or if i'm going to be presented by a glorious collection of mismatched pixels, either the case it runs!_

**Comment by EmilDohne** [comment]
Yeah swapaxes should work! Keep in mind that if youre running the release version of psapi you need to copy the array as swapaxes only changes the internal stride etc. not the actual data. See the discussion below on how to do that

https://github.com/EmilDohne/PhotoshopAPI/discussions/71

In the next version you should be able to see this behaviour change by the psapi making it contiguous internally :)

**Comment by Gofven** [comment]
I've figured it out thanks to #71 you referenced c:
It's due to me not declaring the Color Mode, height, and width when creating a LayeredFile_8bit instance!

Thanks again for the help you provided!!

**Comment by EmilDohne** [comment]
I'm very glad you were able to figure this out! I'll go ahead and close out this ticket but this actually made me figure out a part of the issue mentioned her https://github.com/EmilDohne/PhotoshopAPI/issues/65. Photoshop doesnt actually allow files smaller than 1 pixel which I've failed to catch. The color mode should default to RGB anyways so that shouldnt have been an issue :).

Making the size default initialize to 1 actually also allows one to visually debug the file easily rather than getting hit with some obscure error
